In [3]:
import pandas as pd
import numpy as np

In [4]:
df= pd.read_csv('C:/Users/Mayank Srivastava/Desktop/Minor/dataset.csv')

In [5]:
df.head()

Unnamed: 0  Unnamed: 0.1  No.      Time                   Source  \
0           0             0    1  0.000000          192.168.222.141   
1           1             1    2  0.000259  youtube-ui.l.google.com   
2           2             2    3  0.330808  youtube-ui.l.google.com   
3           3             3    4  0.340927          192.168.222.141   
4           4             4    5  0.341198  youtube-ui.l.google.com   

               Destination Protocol  Length  \
0  youtube-ui.l.google.com  TLSv1.2     708   
1          192.168.222.141      TCP      60   
2          192.168.222.141  TLSv1.2     337   
3  youtube-ui.l.google.com  TLSv1.2      93   
4          192.168.222.141      TCP      60   

                                                Info  Result Src_Port  \
0                                   Application Data       0    46978   
1  https > 46978 [ACK] Seq=1 Ack=655 Win=64240 Len=0       0    https   
2  Application Data, Application Data, Applicatio...       0    https   
3                                   Application Data       0    46978   
4  https > 46978 [ACK] Seq=284 Ack=694 Win=64240 ...       0    https   

  Dest_Port  SourcePort  DestinationPort  Source_id  Destination_id  \
0     https     46978.0            443.0          1              48   
1     46978       443.0          46978.0         31               4   
2     46978       443.0          46978.0         31               4   
3     https     46978.0            443.0          1              48   
4     46978       443.0          46978.0         31               4   

   Destination_Port  Source_Port  
0                 6         2440  
1              2439            5  
2              2439            5  
3                 6         2440  
4              2439            5

In [6]:
df['Source_id'] = df.groupby(['Source']).ngroup()
df['Destination_id'] = df.groupby(['Destination']).ngroup()
df['Destination_Port'] = df.groupby(['DestinationPort']).ngroup()
df['Source_Port'] = df.groupby(['SourcePort']).ngroup()

In [7]:
df.head()

Unnamed: 0  Unnamed: 0.1  No.      Time                   Source  \
0           0             0    1  0.000000          192.168.222.141   
1           1             1    2  0.000259  youtube-ui.l.google.com   
2           2             2    3  0.330808  youtube-ui.l.google.com   
3           3             3    4  0.340927          192.168.222.141   
4           4             4    5  0.341198  youtube-ui.l.google.com   

               Destination Protocol  Length  \
0  youtube-ui.l.google.com  TLSv1.2     708   
1          192.168.222.141      TCP      60   
2          192.168.222.141  TLSv1.2     337   
3  youtube-ui.l.google.com  TLSv1.2      93   
4          192.168.222.141      TCP      60   

                                                Info  Result Src_Port  \
0                                   Application Data       0    46978   
1  https > 46978 [ACK] Seq=1 Ack=655 Win=64240 Len=0       0    https   
2  Application Data, Application Data, Applicatio...       0    https   
3                                   Application Data       0    46978   
4  https > 46978 [ACK] Seq=284 Ack=694 Win=64240 ...       0    https   

  Dest_Port  SourcePort  DestinationPort  Source_id  Destination_id  \
0     https     46978.0            443.0          1              48   
1     46978       443.0          46978.0         31               4   
2     46978       443.0          46978.0         31               4   
3     https     46978.0            443.0          1              48   
4     46978       443.0          46978.0         31               4   

   Destination_Port  Source_Port  
0                 6         2440  
1              2439            5  
2              2439            5  
3                 6         2440  
4              2439            5

In [8]:
df[df['SourcePort'] < 0] = 0
df[df['DestinationPort'] < 0] = 0
df['Source_Port'].fillna(0)

0        2440
1           5
2           5
3        2440
4           5
         ... 
96446       3
96447    3258
96448    3258
96449       3
96450    3258
Name: Source_Port, Length: 96451, dtype: int64

In [9]:
df.to_csv('C:/Users/Mayank Srivastava/Desktop/Minor/dataset.csv')

In [10]:
features= ['Source_id', 'Destination_id','Source_Port','Destination_Port']
X= df[features]

In [11]:
Y=df.Result

In [12]:
X.head()

Source_id  Destination_id  Source_Port  Destination_Port
0          1              48         2440                 6
1         31               4            5              2439
2         31               4            5              2439
3          1              48         2440                 6
4         31               4            5              2439

In [13]:
#Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [14]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
X_train

array([[ 1.0970968 , -0.32569226, -0.7737275 ,  2.23989213],
       [-0.40639746, -0.2142472 , -0.77556195,  0.47226356],
       [-0.25604803, -0.32569226,  1.68994262, -0.73388299],
       ...,
       [-0.40639746, -0.2142472 , -0.77556195,  0.96412543],
       [-0.40639746, -0.2142472 , -0.77556195,  0.44875546],
       [-0.25604803, -0.32569226,  1.50007676, -0.73388299]])

In [16]:
X_test

array([[-0.25604803, -0.32569226,  0.52506509, -0.73388299],
       [-0.40639746, -0.2142472 , -0.77556195, -0.18957997],
       [ 3.05163933, -0.32569226, -0.7737275 ,  1.94513668],
       ...,
       [-0.40639746, -0.2142472 , -0.77556195,  0.63953276],
       [-0.40639746, -0.2142472 , -0.77556195,  1.80680053],
       [-0.40639746, -0.2142472 , -0.77556195,  1.33302182]])

In [22]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 15 , max_depth= 1, criterion = 'entropy',  random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=1, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=15,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [18]:
y_pred = classifier.predict(X_test)
print(y_pred)

[1 0 0 ... 0 0 0]


In [23]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(Y_test, y_pred))


Accuracy: 0.9808719091804469


In [24]:
from sklearn.metrics import precision_recall_fscore_support 
precision_recall_fscore_support(Y_test, y_pred, average='macro')


(0.9789767547857794, 0.9830485115766263, 0.9806407450907055, None)